flowchart TD
    code2schema__analyzer["code2schema.analyzer<br/>19 funcs"]
    code2schema__cli["code2schema.cli<br/>2 funcs"]
    code2schema__codegen["code2schema.codegen<br/>10 funcs"]
    code2schema__core["code2schema.core<br/>16 funcs"]
    code2schema__cli ==>|7| code2schema__analyzer
    code2schema__cli ==>|4| code2schema__codegen
    code2schema__cli -->|1| code2schema__core
