"""
code2schema.codegen
~~~~~~~~~~~~~~~~~~~
Generatory wyjściowe:
  - JSON  (domyślny)
  - Proto (gRPC .proto)
  - Markdown summary
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

from code2schema.core.models import CQRSRole, SchemaIR


# ── JSON ──────────────────────────────────────────────────────────────────────

def to_json(schema: SchemaIR, indent: int = 2) -> str:
    """Serializuje SchemaIR do JSON."""
    return json.dumps(schema.model_dump(), indent=indent, default=str)


def write_json(schema: SchemaIR, path: Path) -> None:
    path.write_text(to_json(schema), encoding="utf-8")


# ── Proto ─────────────────────────────────────────────────────────────────────

def to_proto(schema: SchemaIR) -> str:
    """Generuje .proto z modelu CQRS."""
    lines: list[str] = [
        'syntax = "proto3";',
        "",
        f"// Generated by code2schema v0.1",
        f"// Modules: {len(schema.modules)}, "
        f"Commands: {len(schema.commands())}, "
        f"Queries: {len(schema.queries())}",
        "",
        "package code2schema;",
        "",
        "message Request  { string payload = 1; }",
        "message Response { string result  = 1; bool success = 2; }",
        "",
        "service Code2Schema {",
    ]

    for func in schema.all_functions():
        if func.role in (CQRSRole.QUERY, CQRSRole.COMMAND, CQRSRole.ORCHESTRATOR):
            suffix = func.role.value.capitalize()
            safe_name = _safe_proto_name(func.name)
            lines.append(
                f"  rpc {safe_name}{suffix} (Request) returns (Response);"
            )

    lines += ["}", ""]
    return "\n".join(lines)


def write_proto(schema: SchemaIR, path: Path) -> None:
    path.write_text(to_proto(schema), encoding="utf-8")


# ── Markdown summary ──────────────────────────────────────────────────────────

def to_markdown(schema: SchemaIR) -> str:
    """Zwraca czytelne Markdown podsumowanie."""
    funcs = schema.all_functions()
    total = len(funcs)
    commands = len(schema.commands())
    queries = len(schema.queries())
    orchestrators = len(schema.orchestrators())

    lines: list[str] = [
        "# Code2Schema Report",
        "",
        f"**Modules:** {len(schema.modules)}  "
        f"**Functions:** {total}  "
        f"**Workflows:** {len(schema.workflows)}",
        "",
        "## CQRS Distribution",
        "",
        f"| Role | Count |",
        f"|------|-------|",
        f"| Query | {queries} |",
        f"| Command | {commands} |",
        f"| Orchestrator | {orchestrators} |",
        "",
    ]

    if schema.rules:
        lines += ["## Quality Rules", ""]
        for rule in schema.rules:
            icon = "🔴" if rule.severity == "error" else "🟡"
            lines.append(f"- {icon} **{rule.id}** `{rule.target}` — {rule.condition}")
        lines.append("")

    if schema.workflows:
        lines += ["## Workflows (Orchestrators)", ""]
        for wf in schema.workflows[:20]:  # max 20
            steps = " → ".join(s.callee for s in wf.steps[:8])
            lines.append(f"- **{wf.name}**: `{wf.entry}` → {steps}")
        lines.append("")

    return "\n".join(lines)


def write_markdown(schema: SchemaIR, path: Path) -> None:
    path.write_text(to_markdown(schema), encoding="utf-8")


# ── helpers ───────────────────────────────────────────────────────────────────

def _safe_proto_name(name: str) -> str:
    """CamelCase dla nazw proto RPC."""
    return "".join(part.capitalize() for part in name.split("_"))
